### ISSUE TITLE
Add parent information into fparser2 AST

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#102]
Currently the nodes in the AST produced by fparser2 do not hold the identity of their parent. This is needed in e.g. https://github.com/stfc/PSyclone/issues/27 where I'm currently retrospectively adding this information as I walk down the AST. I'm not about to launch into implementing this while @rupertford is busy making substantial changes to the code base.

**Comment by arporter** [comment]
An extra note to say that this functionality is also needed in order to modify the AST. For instance, to add a variable declaration we need to find the correct part of the AST. Currently there is no way of doing this from an arbitrary location in the AST as there is no parent information and no way to get to the root node.

**Comment by pelson** [comment]
I haven't thought about the implications much, but the circular references sound less than ideal, and would make it a little bit harder to swap new nodes in-place of old ones.

As an alternative suggestion, in https://github.com/stfc/fparser/issues/105#issuecomment-468690505 I added a suggestion that a standard Visitor implementation would be handy within fparser. With such a template, the following code gives us a lookup for any given node's parent:

```
import weakref

class ParentLookup(Visitor):
    def __init__(self, program):
        # Maps id(node) to parent instance.
        self.parent_of = weakref.WeakValueDictionary()
        super().__init__(program)

    def visit_object(self, node):
        for child in children(node) or []:
            self.parent_of[id(child)] = node
            self.visit(child)


parent = ParentLookup(program)

for match in NodeMatcher(program).matches:
    print(match, " parent ", parent.parent_of[id(match)])
```

Python's GC is sufficiently good that you don't have to worry too much about circular references, but it is nice to keep them to a minimum still IMO, so the weakref dict solves precisely this issue.

**Comment by MatthewHambley** [comment]
From a user's point of view I really don't want to have to build up a tree of parentage information every time I want to track upwards in the tree. The ability to discover the parent of an arbitrary node really feels like functionality the tree should provide.

Here is an example of something I want to do right now: Check that all pointer variables are initialised on declaration. Except, of course, return variables from functions can not be initialised so it would be wrong to complain that they aren't.

In this case I have a set of arbitrary nodes, the declarations, but in order to know if I need to check them I need to know their context, whether they are in a function and further more, are the return variable.

This can be generalised as follows:

1. Find all instances of a specified node type within a specified sub-tree
2. Backtrack up the tree to discover context

For me the visitor pattern isn't really applicable here. It seems more suited to situations where something is to be done to all (or many) nodes, which is not the case here. Of course a tree search will probably be implemented as a descent but I really don't want to have to care about that.

**Comment by arporter** [comment]
I was planning to attempt to add parent information into the parse tree as it is constructed, not retrospectively. I could even try that now given the Christmas hiatus...

**Comment by arporter** [comment]
I think I have it working. I just need to sort out the testing.

**Comment by rupertford** [comment]
PR #230 has been merged to master. Closing this issue.
