### ISSUE TITLE
fparser2 reports invalid Fortran for "use module_name, only:"

### ISSUE THREAD

**Issue by TeranIvy** [stfc/fparser#118]
Apparently, `use module_name, only:` is valid Fortran. The example used is below.
```
program test_module_name
  use module_name, only:
  implicit none
  integer :: i1, i2, i3
  i1 = 1; i2 = 2; i3 = 3
  write(*,*) "i1 = ", i1
end program test_module_name
```
This example compiles with Intel 17.0.1 and Gnu 6.1.0 and the effect of `use module_name, only:`  is that nothing from the `module_name` gets used so it is effectively waste of code.

fparser2 reports invalid Fortran:
```
...
    raise FortranSyntaxError(error)
fparser.two.utils.FortranSyntaxError: at line 2
```

Perhaps raising a warning for this case would be useful.

**Comment by rupertford** [comment]
I've just looked at the Fortran2003 spec [https://wg5-fortran.org/N1601-N1650/N1601.pdf] and on page 468 it gives an example of `use module_name, only :`. The reason for doing this would be to keep variables inside the module in-scope e.g. when two children subroutines called from a parent subroutine want to use the module, the information would go out-of-scope when in the parent subroutine. However, whilst adding `use module_name, only :` disallows the parent subroutine from using the data, it does keep the module in-scope so that the children subroutines can share data from within the module.

**Comment by rupertford** [comment]
Created empty_only branch to work on this

**Comment by TeranIvy** [comment]
I learned something about F2003 here, thanks for explaining! As I said yesterday in Telco, I am happy to take on the review after PR is issued.

**Comment by rupertford** [comment]
Thanks @TeranIvy. I'm about to create a PR and assign it to you.

**Comment by TeranIvy** [comment]
PR #122 merged, closing issue.
