### ISSUE TITLE
fparser2 fails on case mismatch in type declaration

### ISSUE THREAD

**Issue by MartinDix** [stfc/fparser#120]
With this example
```
module test

type abc
   real :: x
end type ABC

end module test
```
fparser2 fails with
```
    raise NoMatchError(errmsg)
fparser.two.utils.NoMatchError: at line 7
>>>end module test
```
Case mismatches with names in ```end module``` and ```end subroutine``` don't cause a problem.

**Comment by rupertford** [comment]
I can reproduce the bug.
Created branch typedecl_case_bug to work on this.

**Comment by rupertford** [comment]
@MartinDix, there is a fix on the branch if you'd like to test it out. It will take a little while to make it onto master as I need to add some new tests and documentation.

**Comment by rupertford** [comment]
The fix was pretty simple. There is a test that the start and end names are the same in the BlockBase class (if this check is requested by the subclass). This was doing a simple equality check so I modified it to be case insensitive.

I also noticed that fparser was signalling that the error was on the following line. I took the opportunity to improve the error handling so that it now reports the correct line and I have also simplified the use of SyntaxError so that it handles outputting line numbers. This should make it easier to add a SyntaxError exception where needed.

**Comment by MartinDix** [comment]
Thanks, This branch fixes the problem with the example and in the original full routine.

**Comment by rupertford** [comment]
That's good to hear. It should be on master soon so will be in the next release. Out of interest, if you don't mind me asking, what is your reason for using fparser?

**Comment by MartinDix** [comment]
> That's good to hear. It should be on master soon so will be in the next release. Out of interest, if you don't mind me asking, what is your reason for using fparser?

I'm running it over the UM source code looking for possibly unused namelist variables, UM ticket 4418.

**Comment by rupertford** [comment]
Ah, OK, great. I see you are already aware of ticket 4398. I'm working through the associated issues to make fparser2 fully parse the UM.

Are you OK for me to mention your example as a use case in the future i.e. that fparser2 has been used to help find potential problems in Fortran?
