### ISSUE TITLE
[fparser2] Parsing very slow for some expressions

### ISSUE THREAD

**Issue by reuterbal** [stfc/fparser#236]
Hi,

we recently tried how far we would get parsing our code base with fparser2. While the vast majority of files was parsed successfully (failures mostly due to the lack of support for preprocessor directives), we noticed some odd behaviour on two source files.

Characteristic for both files are lengthy, multi-line scalar algebraic statements, which seem to parse extremely slow (in fact, 24 hours (!) were not enough to parse one file).
@mlange05 and I investigated the behaviour a bit and compiled a smallish example from those files that can reproduce the behaviour:
```python
from fparser.common.readfortran import FortranStringReader
from fparser.two.parser import ParserFactory
from time import time

code = \
    'SUBROUTINE SOME_ROUTINE(ZT,ZRH,ZRHOA,ZX)\n' + \
    'ZNTOT =-0.002954125078716302 - 0.0976834264241286*ZT +       &\n' + \
    ' &     3.635186504599571E-10*ZT**3*LOG(ZRH)*LOG(ZRHOA)**2 +  &\n' * 10 + \
    ' &     (0.0001357509859501723*LOG(ZRHOA)**3)/ZX\n' + \
    'END SUBROUTINE SOME_ROUTINE'

reader = FortranStringReader(code)
f2008_parser = ParserFactory().create(std='f2008')
start = time()
f2008_parser(reader)
print('Elapsed: %.3f sec.' % (time() - start))
```
which takes about 3 minutes (!) to parse. This was tested with different versions of Python 3 (3.7.1 being the latest) and fparser 0.0.10 from PyPi as well as latest master.

The original version of this assignment in the Fortran code (of which there are multiple) spans 35 lines, all of a similar structure as the one above. Since it is a sum we could simply single out some lines and noticed that not all take that long (some in the order of 1us, others in the order of seconds). In the above example the offending line is the second in the assignment, i.e.,
```fortran
3.635186504599571E-10*ZT**3*LOG(ZRH)*LOG(ZRHOA)**2
```
Including the line multiple times (thus the `'...' * 10`) worsened the problem significantly: each appending of that line increased parse time by a factor of 2-3.

Running above example with cProfile and looking at the call graph (click to enlarge) shows that for this relatively short expression more than 13 million invocations of `Base::__new__` and more than 4 million calls to `match` are made. This seems excessive.
![fparser-issue](https://user-images.githubusercontent.com/6384870/73280242-2824b800-41e6-11ea-8672-14c7ed1ed7e7.png)

Have you noticed similar behaviour before?
Educated guess is that the try-fail-type of recursive matching below might need some help.
https://github.com/stfc/fparser/blob/d1f91a0454dd70cfdc5ae2531ae294f96f040fa4/src/fparser/two/utils.py#L372-L380

Since this is quite fundamental stuff do you have any suggestions or ideas on how to overcome this?

**Comment by rupertford** [comment]
Hi @reuterbal. Many thanks for the comprehensive information. Yes, we have had issues with excessive numbers of matches before. In that case it was very large data statements and we were getting failures due to too much recursion (after running for a long time).

The problem there was, and I suspect the problem here is, to do with the matching on particular rules being too loose. The way the fparser2 works is that it tries a set of rules in turn. If any of these rules match it recurses to all children rules of this rule in turn and continues to recurse until there is no match, or until it actually finds a match for the full input. If certain matches are loose i.e. they could reject the match but they don't, then fparser2 may need to recurse down a long way before rejecting certain matches. I suspect with expressions there are lots of potential different types of matches which is causing the excessive amount of recursion.

The reason you are picking up on the code in utils.py is that this is where the recursion to children happens for all matches.

I'll take a look and see what is going on.

**Comment by rupertford** [comment]
OK, I think I've found the main culprit.
On my laptop your example took 313.4s.
With the change it now takes 0.4s.

I'll put it on a branch and make a PR.

**Comment by rupertford** [comment]
Created branch 236_slow_expressions

**Comment by rupertford** [comment]
The problem was that the binary-operator matching class defaults to splitting matches on the RHS of a string but was trying to match the LHS of the string first. In most cases the rules will not match (there are many rules and only one valid combination). If either the rhs or lhs fail to match then binary-operator match fails. Therefore it is quicker to test the simpler (smaller) string first as it will require fewer rules to determine if it is valid or not. This is particularly true for complex expressions.

**Comment by rupertford** [comment]
For some reason the writing out of the resultant code is very slow.

**Comment by rupertford** [comment]
This example has quite a deep hierarchy of objects and using the original `'%s %s %s' % tuple(self.items)` for the `str` method was very slow. Changing to use `" ".join(...)` speeds things up significantly (from >10mins and still not finished to 0.4s on my laptop where both timings include parsing the code).

**Comment by hiker** [comment]
Great that someone looks at this, I was always wondering about the parsing speed and intended to check that myself ;)
Note that we had the discussion about "".join() vs string concatenation in psyclone as well (iirc. the visitor pattern creates the output code uses concatenation). I think I didn't get traction in the past because parsing was just SO slow (like 95% of the overall processing time) - that might finally change this :) :+1:

**Comment by reuterbal** [comment]
Wow, that was quick! Many thanks!
I'll give it a try and report back.
