### ISSUE TITLE
format-specifier does not match if '=' and concat are used

### ISSUE THREAD

**Issue by reuterbal** [stfc/fparser#253]
Sorry for finding the next edge case (narrowing down the last frontend failures and they are getting increasingly ugly). After simplifying the original offending line, this seems to be the minimum example to produce the problem:
```python
>>> from fparser.common.readfortran import FortranStringReader
>>> from fparser.two.parser import ParserFactory 
>>> fcode = '''
... PROGRAM FOO
... WRITE (6, '("write some=""'//'text'//'""")')
... END PROGRAM FOO
... '''
>>> reader = FortranStringReader(fcode)
>>> parser = ParserFactory().create(std='f2008')
>>> ast = parser(reader)
Traceback (most recent call last):
  File "/.../src/fparser/two/Fortran2003.py", line 237, in __new__
    return Base.__new__(cls, string)
  File "/.../src/fparser/two/utils.py", line 407, in __new__
    raise NoMatchError(errmsg)
fparser.two.utils.NoMatchError: at line 3
>>>WRITE (6, '("write some=""'//'text'//'""")')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../src/fparser/two/Fortran2003.py", line 241, in __new__
    raise FortranSyntaxError(string, "")
fparser.two.utils.FortranSyntaxError: at line 3
>>>WRITE (6, '("write some=""'//'text'//'""")')
```

It works fine as soon as you either replace `=` by whitespace or remove the string concatenation.

**Comment by arporter** [comment]
It took me a while to even understand what that should do! I've a nasty memory that our string matching is not as robust as it should be so I'll have a dig...

**Comment by reuterbal** [comment]
Yes, same here... I spent probably 80% of the time from hitting the bug to opening the bug report on understanding the Fortran. It comes from some kind of parameter output where for some reason the format string is built dynamically.

**Comment by arporter** [comment]
I still haven't found the bug but I have found a workaround: if you put "fmt=" before the format specification then all is (apparently) well.

**Comment by arporter** [comment]
The problem seems to be in `Io_Control_Spec`. Its match method only checks for key-value pairs and obviously there are several forms of io-control-spec that may omit the key part. We would then expect one of the 'subclasses' of `Io_Control_Spec` to match. However, `Io_Control_Spec` has a populated `use_names` list but an empty `subclass_names` list. The `Base.match()` method therefore does not do any further checking with subclasses and raises a no-match error instead.
If I copy the `use_names` list into the `subclass_names` list then we get a match and all tests pass.

I've looked at the developers guide and we just have TODOs to explain the purpose of `use_names`! I've grepped through the code and the only place I can seem them being used is in the code at the end of the Fortran2003/8 modules that dynamically creates necessary classes (e.g. the xxx_List classes). Therefore, naming a class in a `use_names` list ensures that it is created but does not add it to the list of classes that are checked when testing for a match.

**Comment by arporter** [comment]
The `use_names` thing was a red herring - although the tests passed, the parse tree produced for new test case was wrong. (We ended up with an `Io_Control_List` that contained entries that were not `Io_Control_Spec`.) The actual problem was in `utils.KeyWordValueBase` which did not check that the LHS of a 'key=val' expression was a valid name.

**Comment by reuterbal** [comment]
Wow, this turned out to be really involved - we owe you a decent cold beverage ;-)

Short follow-up on the `use_names`: My understanding from reading the code was that this is one of essentially two ways of making classes known in the "match hierarchy" 
1/ via `subclass_names` to match in case the class itself doesn't, or 
2/ via `use_names` to announce classes produced as part of the matching (i.e., a part of the result rather than instead). 
The fact that this is used to create the `*_List` classes is something I stumbled across as part of #249. Is this generally correct? Or is there more to it? And yes, I agree that explaining the purpose of both properties in the developers guide would be helpful.

**Comment by arporter** [comment]
One day "when all this is over" a cold beverage would be lovely but I've a nasty feeling I'm only fixing my own bug here :-)

My understanding from looking at the code yesterday is that only `subclass_names` affects the "match hierarchy". `use_names` appears only to be used to 'declare' that certain classes need to be constructed by the code at the end of the module.

**Comment by reuterbal** [comment]
I can confirm that #260 fixes the issue for us. Many thanks!
