### ISSUE TITLE
fparser handles `!f2py` comments as directives

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#268]
Due to its origins in the f2py project, `FortranFileReader` still contains functionality that treats comments beginning with `!f2py` as directives. Essentially, it seems to strip off the `!f2py` and then attempts to parse the remainder of the line as standard Fortran.

In this issue we will investigate whether there is already functionality to control this behaviour and, if there isn't, add some.

**Comment by arporter** [comment]
An alternative is of course to strip-out the handling of f2py directives altogether but I'm not sure about that. Thoughts anyone?

**Comment by arporter** [comment]
Looking at the existing tests in `test_readfortran.py`, two of them include f2py directives. However, in the one that is fixed-format F77 the directive just disappears! It is kept and handled in the F90 version.

**Comment by rupertford** [comment]
I guess you've started implementing a solution, however my thoughts would be that we should not remove the functionality that is there in case this ever gets picked up for use in a new version of f2py (as Peuru originally intended). What I would do instead is disable it by default with an internal switch so that f2py directives are treated as comments by default. Perhaps you are already doing this anyway :-)

**Comment by arporter** [comment]
Yep, that's what I've done :-)
