### ISSUE TITLE
Character string is matched by Scalar_Int_Expr

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#276]
While working on #260 I found that fparser2 would accept:

    '"some-str", end=123'

as a valid io-control-spec-list which it definitely is not. The reason appears to be that `Io_Unit` has `File_Unit_Number` as one of its `subclass_names` and in turn, that has `Scalar_Int_Expr` and this appears to match the character string:

    >>> Fortran2003.Scalar_Int_Expr('"hello"')
    Char_Literal_Constant('"hello"', None)

Since the `Scalar_Int_Expr` is one of the auto-generated classes, I'm not sure why this happens.

**Comment by arporter** [comment]
It seems that ".False." is also accepted as an io-control-spec-list!

**Comment by rupertford** [comment]
The problem is that Scalar_Int_Expr (which is implemented in class Int_Expr) matches an expression (Expr) which can be of any type and then there is a constraint that this expression should return an integer, which is not tested in fparser. Simple tests for expressions that are constants being the correct type are being added in PR #286 which should fix the problems identified in this issue but will not deal with more complicated expressions.

**Comment by arporter** [comment]
#286 has been merged and that does fix this particular issue.
