### ISSUE TITLE
Expr matches an assignment

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#283]
While working on #260 I discovered that doing `Format("a=b")` gives a match because `Expr("a=b")` matches.
The reason for this match is that the rule for StructureConstructor specifies StructureConstructor_2 as a subclass and *that* matches on `[ <keyword> = ] <component-data-source>`. As implied by the strange naming, the implementation of `StructureConstructor_2` refers to R457.b which I can't find in the Fortran2003 standard.

**Comment by arporter** [comment]
![Screenshot from 2021-01-08 12-12-07](https://user-images.githubusercontent.com/17409212/104014376-d254e000-51aa-11eb-9f59-2bc72bb48c55.png)

**Comment by arporter** [comment]
If I remove `StructureConstructor_2` as a subclass of `StructureConstructor` then `Expr('a="b"')` no longer matches but I get other test failures.

**Comment by rupertford** [comment]
Created branch [283_expr_matches_assignment](https://github.com/stfc/fparser/tree/283_expr_matches_assignment)

**Comment by rupertford** [comment]
The `Structure_Constructor_2` class does seem spurious - it is certainly not in the Fortran2003 spec, other than being an exact copy of `R458 component-spec`. I have therefore removed it and updated the tests. The failing tests were due to testing Structure_Constructor_2 and an unrelated issue where the change highlighted a match that was actually failing but had not been recognised as such.

**Comment by rupertford** [comment]
This change fixes the false matching problem in this issue.

**Comment by arporter** [comment]
Can this issue be closed now @rupertford ?

**Comment by rupertford** [comment]
Yes, thanks @arporter. I've just closed it.
