### ISSUE TITLE
Expressions containing -ve exponents cannot be parsed

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#288]
master is currently broken. e.g. the Fortran `zMv = zSST+1.33d-3*zSST` causes a syntax error. If I change the numerical constant to `1.33d3` instead then all is fine. This may be related to the recent bug fix for the slow parsing of expressions @rupertford?

**Comment by rupertford** [comment]
Yes it is almost definitely #237. There was, what looked like, an unnecessary hack that was removed in that PR. There was an additional `is_add` argument that was passed to one of the base classes which did something special for this class - it ignored the negative exponent in a match. It looked like this was just an optimisation rather than to do with correctness.

As I think I said in the associated issue #236, the hack should have not been done the way it was, i.e. it should have been done by specialising the matching class rather than passing a parameter to the base class (I think), so the fix should try to do it the "right" way.

I'll take this issue on seeing as it is my error.

**Comment by rupertford** [comment]
Created branch [288_negative_exponent_error](https://github.com/stfc/fparser/tree/288_negative_exponent_error)

**Comment by rupertford** [comment]
I've found the culprit but do not yet have a solution. The problem is to do with pr #285, the removal of StructureConstructor2. We wondered why it was there and it looks like this is why! Expression matching occurs in a hierarchy, Level5, Level4 ... Level1 and then Primary. Add (+/-) is Level2. Primary includes StructureConstructor, which then tried to match StructureConstructor2. Somehow this acted like a way back up the hierarchy to match again.

StructureConstructor2 is clearly the wrong way to fix this problem so I need to work out why the matching hierarchy is failing then work out a solution.
