### ISSUE TITLE
Use black in CI workflow to automate fixes to pycodestyle errors?

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#348]
@ZedThree has suggested that we add a workflow to GHA that will automatically run `black` to fix any pycodestyle errors.
I've tried doing this locally and almost all of the files get changed so it will be a big bang initially. However, I quite like the results and it's one less thing for the reviewer to have to think about.

What do @rupertford, @sergisiso and @MatthewHambley think?

**Comment by sergisiso** [comment]
I thinks its a good idea. A `.git-blame-ignore-revs` can be added to keep the messages from last time each line was changed (https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html). I also heard of people rewriting all git history applying black since the beginning, but this may be too extreme.

**Comment by arporter** [comment]
We discussed this at the meeting this morning and everyone was in favour. It was noted that it will be a good idea for developers to also apply Black locally (which can be automated in your editor of choice) so as to avoid having to keep pulling back upstream changes.
