### ISSUE TITLE
Confusion around test frameworks

### ISSUE THREAD

**Issue by p-vitt** [stfc/fparser#44]
I'm a little confused about the test frameworks. The github automatic build is passing and the log states that 330 tests passed, whereas 1 failed. The test framework used during automatic build seems to be pytest.
However, [setup.py](https://github.com/stfc/fparser/blob/master/setup.py#L122) implies that nose is used for testing. When I run nose on my local working copy, it finds 120 tests, from which 5 are failing.

Which test frameowrk should be used? Is this somehow related to #38 ?

**Comment by arporter** [comment]
We use py.test, both locally and on travis. However, we have only taken on maintenance of this project relatively recently and some of the original tests make use of nose internally. #38 is only about how we structure the directories containing tests, not the way in which the tests are done. If you fancy cleaning out all uses of nose then feel free. Otherwise we can keep this issue open and we will tackle it.

**Comment by arporter** [comment]
@TeranIvy has fixed this as part of #95 so I'm closing this issue.
